version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_blogio_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: blogiodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  redisinsight:

networks:
  app-network:
    driver: bridge
